import { colors, spacing, typography } from "@/styles";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FB",
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
    gap: spacing.lg,
  },
  section: {
    gap: spacing.md,
  },
  sectionHeader: {
    gap: 4,
  },
  sectionTitle: {
    ...typography.title,
    fontSize: 24,
    color: colors.text,
  },
  sectionSubtitle: {
    ...typography.caption,
    color: colors.mutedText,
    lineHeight: 17,
  },
  heroCard: {
    backgroundColor: "#EAF1FF",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#D2E2FF",
    padding: spacing.lg,
    gap: spacing.xs,
    shadowColor: "#8EB3FF",
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 22,
    elevation: 4,
  },
  heroCardLift: {
    backgroundColor: "#EEF9F1",
    borderColor: "#CFE7D4",
    shadowColor: "#7BC18E",
  },
  heroCardCare: {
    backgroundColor: "#FFF4EA",
    borderColor: "#F3D4B7",
    shadowColor: "#E7A56C",
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  heroEyebrow: {
    ...typography.caption,
    color: "#4C6EA9",
    textTransform: "uppercase",
    letterSpacing: 0.7,
    fontWeight: "700",
  },
  heroEyebrowLift: {
    color: "#2F7A47",
  },
  heroEyebrowCare: {
    color: "#A35A1F",
  },
  heroMoodBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.72)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  heroMoodEmoji: {
    fontSize: 16,
  },
  heroMoodText: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.text,
    textTransform: "capitalize",
  },
  heroTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "800",
    color: "#162033",
  },
  heroTitleLift: {
    color: "#163321",
  },
  heroTitleCare: {
    color: "#5A2C13",
  },
  heroBody: {
    ...typography.body,
    color: "#52607A",
    lineHeight: 21,
  },
  heroBodyLift: {
    color: "#446152",
  },
  heroBodyCare: {
    color: "#805333",
  },
  heroActionPill: {
    alignSelf: "flex-start",
    marginTop: spacing.xs,
    borderRadius: 999,
    backgroundColor: "#162033",
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  heroActionPillLift: {
    backgroundColor: "#1F5F35",
  },
  heroActionPillCare: {
    backgroundColor: "#6E3A17",
  },
  heroActionText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  heroActionTextLift: {
    color: "#F7FFF8",
  },
  heroActionTextCare: {
    color: "#FFF7F0",
  },
  guidanceCard: {
    backgroundColor: "#FFF9EE",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F3DEC0",
    padding: spacing.md,
    gap: 8,
  },
  guidanceEyebrow: {
    ...typography.caption,
    color: "#9A5A23",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "700",
  },
  guidanceTitle: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
    color: "#7C2D12",
  },
  guidanceBody: {
    fontSize: 14,
    lineHeight: 20,
    color: "#8E5D2C",
  },
  promptCard: {
    marginTop: 4,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 3,
  },
  promptLabel: {
    ...typography.caption,
    color: "#6B7280",
    textTransform: "uppercase",
    letterSpacing: 0.45,
    fontWeight: "700",
  },
  promptText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.text,
    fontWeight: "700",
  },
  statsPanel: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  statPill: {
    flexGrow: 1,
    minWidth: 140,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E4E8F2",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 2,
  },
  statPillLabel: {
    ...typography.caption,
    color: colors.mutedText,
    textTransform: "uppercase",
    letterSpacing: 0.45,
  },
  statPillValue: {
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "800",
    color: colors.text,
  },
  statPillNote: {
    fontSize: 12,
    color: "#667085",
  },
  compareCard: {
    width: "100%",
    backgroundColor: "#FFF6E7",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#F3D8AF",
    padding: spacing.md,
    gap: 5,
  },
  compareCardPressable: {
    borderColor: "#EBCB96",
  },
  compareEyebrow: {
    ...typography.caption,
    color: "#9A5A23",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    fontWeight: "700",
  },
  compareTitle: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "800",
    color: "#7C2D12",
  },
  compareBody: {
    fontSize: 13,
    lineHeight: 19,
    color: "#8E5D2C",
  },
  compareLinkPill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.78)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  compareLinkText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#9A3412",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  halfCard: {
    width: "48%",
  },
  fullCard: {
    width: "100%",
  },
  spotlightCard: {
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 13,
    gap: 6,
  },
  spotlightCardSupportive: {
    backgroundColor: "#F2FAF3",
    borderColor: "#CDE9C8",
  },
  spotlightCardChallenging: {
    backgroundColor: "#FFF5EA",
    borderColor: "#F3D0A6",
  },
  spotlightCardNeutral: {
    backgroundColor: "#F7F8FC",
    borderColor: "#E4E8F2",
  },
  spotlightLabel: {
    ...typography.caption,
    color: "#5F6B7A",
    textTransform: "uppercase",
    letterSpacing: 0.45,
    fontWeight: "700",
  },
  spotlightTitle: {
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "800",
    color: colors.text,
  },
  spotlightDetail: {
    fontSize: 12,
    lineHeight: 17,
    color: "#5F6B7A",
  },
  spotlightLink: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: "700",
    color: "#1D4ED8",
  },
  patternCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E4E8F2",
    paddingHorizontal: 14,
    paddingVertical: 13,
    gap: 4,
  },
  patternCardCool: {
    backgroundColor: "#F3F7FF",
    borderColor: "#D7E3FF",
  },
  patternCardWarm: {
    backgroundColor: "#FFF7ED",
    borderColor: "#F6D8AD",
  },
  patternLabel: {
    ...typography.caption,
    color: "#6A7283",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    fontWeight: "700",
  },
  patternValue: {
    fontSize: 17,
    lineHeight: 21,
    fontWeight: "800",
    color: colors.text,
  },
  patternDetail: {
    fontSize: 12,
    lineHeight: 16,
    color: "#5F6B7A",
  },
  confidenceBadge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.78)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    color: "#5F6B7A",
  },
  signalRail: {
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  signalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E4E8F2",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  signalCardPressable: {
    borderColor: "#D6E4FF",
  },
  signalTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  signalTitle: {
    ...typography.subtitle,
    color: colors.text,
  },
  signalShift: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    color: "#5F6B7A",
  },
  signalConfidence: {
    fontSize: 11,
    color: "#7A8494",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.25,
  },
  signalTrack: {
    position: "relative",
    height: 10,
    borderRadius: 999,
    backgroundColor: "#EEF2FF",
    overflow: "visible",
  },
  signalTrackMid: {
    position: "absolute",
    left: "50%",
    marginLeft: -1,
    top: -3,
    bottom: -3,
    width: 2,
    borderRadius: 999,
    backgroundColor: "#C7D2FE",
  },
  signalThumb: {
    position: "absolute",
    top: -4,
    marginLeft: -8,
    width: 18,
    height: 18,
    borderRadius: 999,
    borderWidth: 3,
    borderColor: "#FFFFFF",
  },
  signalSummary: {
    fontSize: 13,
    lineHeight: 18,
    color: "#5F6B7A",
  },
  signalLinkText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#1D4ED8",
  },
  signalMetaText: {
    fontSize: 12,
    color: "#7A8494",
  },
  stripCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E4E8F2",
    padding: spacing.md,
    gap: spacing.xs,
  },
  stripTitle: {
    ...typography.subtitle,
    color: colors.text,
  },
  mixStrip: {
    flexDirection: "row",
    height: 16,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: "#EEF2FF",
  },
  mixStripSegment: {
    height: "100%",
  },
  mixLegendRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  mixLegendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  mixLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  mixLegendText: {
    fontSize: 12,
    color: "#5F6B7A",
    fontWeight: "700",
  },
  weekdayChart: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 8,
  },
  weekdayCol: {
    flex: 1,
    alignItems: "center",
    gap: 6,
  },
  weekdayCount: {
    fontSize: 10,
    color: "#7A8494",
    minHeight: 12,
  },
  weekdayTrack: {
    width: "100%",
    height: 72,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  weekdayBar: {
    width: "100%",
    borderRadius: 999,
  },
  weekdayLabel: {
    fontSize: 11,
    color: "#5F6B7A",
    fontWeight: "700",
  },
  detailCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E4E8F2",
    padding: spacing.md,
    gap: spacing.sm,
  },
  detailCardTitle: {
    ...typography.subtitle,
    color: colors.text,
  },
  barsWrap: {
    gap: spacing.sm,
  },
  barRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  barLabelWrap: {
    width: 92,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  barEmoji: {
    fontSize: 16,
  },
  barLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.text,
    textTransform: "capitalize",
  },
  barTrack: {
    flex: 1,
    height: 10,
    borderRadius: 999,
    backgroundColor: "#F0F3FA",
    overflow: "hidden",
  },
  barFill: {
    height: "100%",
    borderRadius: 999,
  },
  barValue: {
    width: 20,
    textAlign: "right",
    fontSize: 12,
    fontWeight: "700",
    color: colors.text,
  },
  tagWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  tagSection: {
    gap: spacing.sm,
  },
  tagSectionLabel: {
    ...typography.caption,
    color: "#6A7283",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "700",
  },
  tagPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    backgroundColor: "#EEF4FF",
    borderWidth: 1,
    borderColor: "#D7E3FF",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  tagPillWarm: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    backgroundColor: "#FFF4E7",
    borderWidth: 1,
    borderColor: "#F3D0A6",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  tagText: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.text,
  },
  tagCount: {
    fontSize: 12,
    fontWeight: "800",
    color: "#5F6B7A",
  },
  emptyText: {
    ...typography.body,
    color: colors.mutedText,
    lineHeight: 22,
  },
  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    gap: spacing.sm,
  },
  stateTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.text,
    textAlign: "center",
  },
  stateText: {
    ...typography.body,
    color: colors.mutedText,
    textAlign: "center",
    lineHeight: 22,
  },
});
